version: '3.8'

services:
  data_scheduler:
    build:
      context: ./data_scheduler
      dockerfile: Dockerfile
    container_name: data_scheduler
    environment:
      - GRPC_PORT=50051
      - MONGO_URI=mongodb://admin:password@mongo:27017/content
      - REDIS_URI=redis://redis:6379
    ports:
      - "50051:50051"
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    networks:
      - wibm_network

  fetcher_service:
    build:
      context: ./fetcher_service
      dockerfile: Dockerfile
    container_name: fetcher_service
    environment:
      - DATA_SCHEDULER_URI=data_scheduler:50051
      - ERGAST_API_URL=https://api.jolpi.ca/ergast/f1
      - LOG_LEVEL=INFO
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      - data_scheduler
    networks:
      - wibm_network

  mongo:
    image: mongo:7-jammy
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=content
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - wibm_network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - wibm_network

volumes:
  mongo_data:
  redis_data:

networks:
  wibm_network:
    driver: bridge
